---
Name: omniroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'paymentendpoint/$Identifier/$Status/$ReturnURL/$ID/$OtherID' : 'PaymentGatewayController'
    'dev/payment' : 'PaymentDevelopmentAdmin'
